version: '3.1'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  km4k:
    build:
      dockerfile: Dockerfile.dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
